### ISSUE TITLE
Werkwijze (sprintplanning meeting) met Michel, Emile, Joost en Paul

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#105]
Even meeting met Marc en Joost afwachten en dan inplannen.
Zorgen dat we een goede samenwerking krijgen met Michel en Emile, 2 externen. Bijvoorbeeld sprintmeetings, om de 3 weken met een sprintplanning en sprintreview. 

```[tasklist]
### Tasks
- [x] Meeting met Michel en Emile
- [x] Refinement meetings inplannen (3 wekelijks? Vladimir en Marianne)
- [x] Sprint planning meetings inplannen (3 wekelijks?) Michel, Marianne, Vladimir (en Joost/Wieteke?))
- [x] Sprint reviews inplannen (3 wekelijks?) Michel, Marianne, Vladimir
```
