### ISSUE TITLE
Prioriteren componenten

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#137]
```[tasklist]
### Tasks
- [ ] Lijst maken met alle componenten
- [ ] Per component prioritering aangeven
- [ ] Templates ook meenemen in prioritering?
```
