### ISSUE TITLE
Proces verbeteren leveranciers informeren bij updates

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#29]
Release updatemail vanuit  TO inbox. Max 1x per maand, maar in principe bij elke update
```[tasklist]
### Tasks
- [ ] Lijst van leveranciers opvragen
- [ ] Conceptmail maken (alleen versienr veranderen + uitleg wat veranderd is)
- [ ] Bij eerste update alle leveranciers mailen
```
