### ISSUE TITLE
EPIC: component library zonder proxy

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/component-library#3]
## 1. Epic omschrijving
Componentenbibliotheek onderbrengen bij Nijmegen. Dit om intern controle op de component library te hebben en geen afhankelijkheid van leveranciers. Hierbij wordt wel ondersteuning geboden door leverancier (woweb).

Op basis van intake: https://irvn.sharepoint.com/sites/NijmegenAfstemmingsoverleg/Lists/Intakes/DispForm.aspx?ID=682&ContentTypeId=0x01008DB40EF2E2C16F47964C85F514CE4F3A

## 2. Todo:
```[tasklist]
### Woweb
- [x] de gitlab CI ombouwen naar GitHub actions
- [x] Zorgen dat het resultaat daarvan naar een S3-bucket kan.
```

```[tasklist]
### Devops
- [x] Component library repository verhuizen van Enrise naar Nijmegen: https://github.com/GemeenteNijmegen/component-library
- [x] CDK-project voor infra: https://github.com/GemeenteNijmegen/component-library-infra
- [x] [Component library infra in development succesvol uitrollen](https://github.com/GemeenteNijmegen/component-library-infra/issues/2)
- [x] [Rechten voor woweb om de bucket te vullen inrichten](https://github.com/GemeenteNijmegen/component-library-infra/issues/3)
- [x] Uitzoeken wat proxy doet
- [x] Gegevens overzetten accp
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/7
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/8
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/9
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/11
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/15
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/17
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/16
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/21
- [ ] https://github.com/GemeenteNijmegen/component-library/issues/20
```
