### ISSUE TITLE
Component 'buttons' verbeteren

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#30]
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Documentatie schrijven
- [x] Overleg met Myriam inplannen
- [x] Overdragen aan Woweb + Joost
```

**Comment by iamskip** [comment]
@Michel-Verhoeven Hier is de link naar de buttons. Als je vragen hebt of iets niet duidelijk is, laat het me dan gerust weten: https://shorturl.at/fioy1

**Comment by MariannevanLierop** [comment]
@Michel-Verhoeven , wat is jouw planning qua het oppakken van dit soort tickets? En zet jij dan hier comments zodra het klaar is of wat spreken we af? We hebben ook aparte tickets voor jou, die staan nu in 'In progress' bijv: https://github.com/orgs/GemeenteNijmegen/projects/10?pane=issue&itemId=52361561
