### ISSUE TITLE
Iconen menu Mijn Nijmegen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#31]
Iconen die gemaakt moeten worden voor Mijn Nijmegen ook toevoegen aan de Componentenbibliotheek
```[tasklist]
### Tasks
- [x] Checken iconen van Vladimir
- [x] In eigen sprint infietsen
- [ ] Overdragen aan WoWeb
```

**Comment by iamskip** [comment]
@Michel-Verhoeven @joostvanderborg 
In Figma maak ik gebruik van de iconenset van https://tabler.io/icons.
En voor de toptaken: https://www.opengemeenten.nl/producten/iconenset

**Comment by joostvanderborg** [comment]
Ik:
- kijk wat nodig is voor Mijn Nijmegen (menu)
- Zoek in deze sets wat kan en mag
- Zet dat in Mijn Nijmegen (test) en bespreek volgende meeting
- Daarna in componentenbieb zetten (zelf)

**Comment by joostvanderborg** [comment]
Tabler-icons zijn MIT-licensed, die zouden we kunnen gebruiken. Als experiment ze in Mijn Nijmegen aan het inbouwen.

de opengemeenten-set vereist attributie ([CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode)), da's niet erg, maar waar we dat zouden moeten doen is onopgelost.
