### ISSUE TITLE
Componenten van Mijn Nijmegen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#32]
Als de eerste nieuwe componenten live zijn in comp biblio kunnen we de componenten van Mijn Nijmegen overdragen aan Woweb (bijv sidenav)

```[tasklist]
### Tasks
- [ ] Ontwerp controleren in figma
- [ ] Documentatie schrijven
- [ ] Overdragen aan Woweb + Joost
- [ ] Woweb developen in comp biblio
```
