### ISSUE TITLE
'Typography'

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#41]
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Documentatie schrijven
- [x] Overleg met Myriam
- [x] Overdragen aan Woweb + Joost
```

**Comment by iamskip** [comment]
@Michel-Verhoeven Hier is de link naar de buttons. Als je vragen hebt of iets niet duidelijk is, laat het me dan gerust weten: https://shorturl.at/gpxz7
