### ISSUE TITLE
Component 'colours'

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#42]
```[tasklist]
### Tasks
- [x] Ontwerpen in figma
- [x] Meeting met Paul wat onze kleuren worden
- [x] Documentatie schrijven
- [x] Overdragen aan Woweb + Joost
```
