### ISSUE TITLE
Grid - UX

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#43]
Vladimir voegt nog refinement toe (Joost eventueel vragen)

We nemen de grids van Den Haag over. Benaming voor tokens moeten gemaakt worden voor Michel. Token studio gebruiken.

```[tasklist]
### Tasks
- [x] Link ontwerp in dit ticket zetten --> Vladimir
- [x] Gesprek met Michel plan van aanpak --> Vladimir
- [x] Gesprek met gast van NL design system --> Vladimir
- [x] Ontwerpen marges etc in figma --> Vladimir
- [x] Documentatie schrijven --> Vladimir
- [x] Vertalen naar tokens --> Joost
- [x] Grids ontwikkelen
- [x] Overdragen aan Woweb
```

**Comment by iamskip** [comment]
@joostvanderborg https://www.figma.com/file/g3AieWAFD3NtkbDDTTFC30/Novio---Nijmegen-Design-System?type=design&node-id=38-6&mode=design
