### ISSUE TITLE
Toegankelijkheid Pandosearch fixen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library#53]
Onze toegankelijkheidsspecials Els Groffen heeft wat toegankelijkheidsissues met searchpagina's gevonden (met Pandosearch). Proud Nerds geeft aan deze niet te beheren/Pandosearch levert alleen content (via API). @Michel-Verhoeven, zijn onderstaande punten op te lossen in de componentenbibliotheek? Waarna ProudNerds de verbeterde componenten dan kan invoeren op nijmegen.nl? Zodat de toegankelijkheidsissues zijn opgelost? Weet jij dit?

### Informatie uit mail:

- Uit de audit van nijmegen.nl, blijkt dat er op de pagina’s die gegenereerd worden door Pandosearch, het een en ander verbeterd moet worden op het gebied van digitale toegankelijkheid.

- **1.3.1 Info en relaties**
Op pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477901764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=DVqgO1x1YEzV8sOfSyJvwwCqJldRqW9zH6nUYQ%2BgCFY%3D&reserved=0) kan er gefilterd worden op document type en categorie. Het is momenteel niet programmatisch te bepalen wat de actieve categorie of document type is. Dit wordt momenteel alleen aangegeven met een pseudo-element in de vorm van een driehoekje.
Op de herschaalde versie van pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477908255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=GbbDKII5ksABY6J7ttlIE1uo1zV1nbip4cvpQHGMRj4%3D&reserved=0) staan bovenaan de pagina de kopteksten "Filter results" en "Resultaten voor "pdf"". Omdat deze beide zijn opgemaakt met een `<h1>` element, maakt dit van de koptekst "Filter results", wanneer het menu niet is uitgeklapt, een kop zonder content.

Het volgende wordt niet afgekeurd, maar kan wel worden verbeterd:
Op pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477914066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=hhDqA%2FLvrxlr%2BeP5jrwBkzwWXY%2BmyHnEXU87yWRSnlw%3D&reserved=0) staat onderaan de pagina een paginering. Het `<a>` element met het icoon van de 'chevron' naar links heeft een `role="button` gekregen. Het is beter daadwerkelijk een `<button>` element te gebruiken in dit geval.

**2.4.4 Linkdoel**
Op pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477919527%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=2VbGRzdo29zFPhtQ7Mk7P7ccQ%2BCCP3%2Fuvsj1uIruA4c%3D&reserved=0) staan onderaan te pagina twee links met de alternatieve teksten "Vorige" en "Volgende". Wanneer deze links met een toetsenbord interface worden geactiveerd, verspringt de focus van deze links naar de knop met het loep-icoon bovenaan de pagina. Hierdoor komt het linkdoel niet overeen met het gedrag van de link; dit maakt van "Vorige" en "Volgende" onjuiste linkdoelen.

**3.1.2 Taal van de onderdelen**
Het volgende wordt niet afgekeurd, maar kan wel worden verbeterd: Op de herschaalde versie van pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477925019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=3CYB3dDLr%2Fz1ZK1b5bhLCn60DpQLd2ipcWnkQ%2FiSnBE%3D&reserved=0) staat bovenaan de pagina de tekst [lang lang="en"] "Filter results" [/lang]. Er is momenteel geen taalaanduiding aanwezig. Het advies is deze tekst in het Nederlands aan te bieden op deze pagina.
```[tasklist]
### Tasks
- [ ] Uitzoeken of inderdaad via de component library wijzigingen gedaan kunnen worden aan hoe zoekresultaten gegenereerd worden. (Uitleg op https://componenten.acc.nijmegen.nl/v6.3.2/components/detail/searchresults-template.html). Deze laadt momenteel niet omdat het domein via de Security-headers geblokkeerd is. Dit pakken wij als gemeente nijmegen separaat op als issue opvoeren in de component-library-infra repository, moet door devops gefixt worden.
- [ ] Contact tussen Michel en Devops nodig?
- [ ] Contact tussen Els en Michel nodig?
- [ ] Woweb verbeterd component
- [ ] ProudNerds pakt nieuwe componenten op voor nijmegen.nl
```

**Comment by MariannevanLierop** [comment]
@joostvanderborg , wil jij de samenvatting hierboven zetten?

**Comment by joostvanderborg** [comment]
@MariannevanLierop bij deze. Als we woleb hiernaar kunnen laten kijken?

**Comment by MariannevanLierop** [comment]
Stel dat Woweb dit in comp biblio kan fixen, dan is Nijmegen.nl daarmee niet verbeterd toch? Dus dan moet ProudNerds het uit de comp biblio halen voor nijmegen.nl?

**Comment by MariannevanLierop** [comment]
@Michel-Verhoeven, wij ondervinden toegankelijkheidsissues door Pandosearch. Zijn dit dingen die d.m.v. de componentenbiblitoheek verbeterd kunnen worden? Zie uitleg in omschrijving hierboven. We horen graag of jij denkt dat de componentenbiblio updaten het probleem kan verhelpen en of jij dit kan doen. We kunnen ook even bellen! Groetjes Marianne

**Comment by Michel-Verhoeven** [comment]
@MariannevanLierop Ik heb even wat onderzoek gedaan naar de verschillende punten, hierbij mijn reactie. Samenvattend denk ik dat er aan de componenten bibliotheek geen update nodig is maar de optimalisaties voornamelijk aan de nijmegen.nl kant zitten.

> * **1.3.1 Info en relaties**
>   Op pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477901764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=DVqgO1x1YEzV8sOfSyJvwwCqJldRqW9zH6nUYQ%2BgCFY%3D&reserved=0) kan er gefilterd worden op document type en categorie. Het is momenteel niet programmatisch te bepalen wat de actieve categorie of document type is. Dit wordt momenteel alleen aangegeven met een pseudo-element in de vorm van een driehoekje.

Als je [in de docs](https://componenten.nijmegen.nl/v6.3.2/components/detail/facets-advanced.html) onder het tabje "notes" kijkt zie je een voorbeeld van `facetData` waarbij per item in `facets` een `active: true` meegeven kan worden, hiermee kun je in mijn optiek programmatisch bepalen welke facet actief is


> Op de herschaalde versie van pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477908255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=GbbDKII5ksABY6J7ttlIE1uo1zV1nbip4cvpQHGMRj4%3D&reserved=0) staan bovenaan de pagina de kopteksten "Filter results" en "Resultaten voor "pdf"". Omdat deze beide zijn opgemaakt met een `<h1>` element, maakt dit van de koptekst "Filter results", wanneer het menu niet is uitgeklapt, een kop zonder content

Ik zie dit op nijmegen.nl inderdaad ook maar [in de docs](https://componenten.nijmegen.nl/v6.3.2/components/detail/facets-advanced.html) onder het kopje html zie ik dat een button wordt gebruikt (en het ook als button element wordt gerenderd), is dit dus niet een fout in de html op nijmegen.nl?


> Het volgende wordt niet afgekeurd, maar kan wel worden verbeterd:
Op pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477914066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=hhDqA%2FLvrxlr%2BeP5jrwBkzwWXY%2BmyHnEXU87yWRSnlw%3D&reserved=0) staat onderaan de pagina een paginering. Het <a> element met het icoon van de 'chevron' naar links heeft een role="button gekregen. Het is beter daadwerkelijk een <button> element te gebruiken in dit geval.

Ik begrijp dit punt maar ik begrijp de keuze van de developer ook wel. Bij een eerste pagina is dit element disabled omdat er geen pagina terug is. Het `href` attribuut kan daarbij ook niet gevuld worden omdat er geen link naar een pagina terug is. Het `href` attribuut is echter wel een verplicht attribuut bij het gebruik van een a tag behalve als je het `role` attribuut wijzigt, zoals in dit geval naar button. In mijn optiek is het in dit geval correct, de link fungeert nu even "tijdelijk" als een disabled button. Op pagina 2 wordt het `href` attribuut wel gevuld omdat je nu een link hebt naar de pagina terug. Het enige schoonheidsfoutje hier (in mijn optiek) is dat het `role` attribuut nog steeds gevuld blijft met de waarde `button`, een optimalisatie zou zijn om vanaf pagina 2 hier het `role` attribuut weg te halen. @joostvanderborg ook graag jouw mening hierover.

> 2.4.4 Linkdoel
Op pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477919527%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=2VbGRzdo29zFPhtQ7Mk7P7ccQ%2BCCP3%2Fuvsj1uIruA4c%3D&reserved=0) staan onderaan te pagina twee links met de alternatieve teksten "Vorige" en "Volgende". Wanneer deze links met een toetsenbord interface worden geactiveerd, verspringt de focus van deze links naar de knop met het loep-icoon bovenaan de pagina. Hierdoor komt het linkdoel niet overeen met het gedrag van de link; dit maakt van "Vorige" en "Volgende" onjuiste linkdoelen.

Dit lijkt op een klein foutje op nijmegen.nl. Als namelijk op het zoekformulier voor de website ( `<form class="autocomplete autocomplete__form" ... `) het attribuut `tabindex="-1"` wordt toegevoegd dan zal de focus op het pagination navigatie element blijven.

>Het volgende wordt niet afgekeurd, maar kan wel worden verbeterd: Op de herschaalde versie van pagina [https://www.nijmegen.nl/zoeken/?q=pdf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fzoeken%2F%3Fq%3Dpdf&data=05%7C02%7Cj.van.der.borg%40nijmegen.nl%7C327b1b9c88334973df1208dc27d5594a%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638429044477925019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=3CYB3dDLr%2Fz1ZK1b5bhLCn60DpQLd2ipcWnkQ%2FiSnBE%3D&reserved=0) staat bovenaan de pagina de tekst [lang lang="en"] "Filter results" [/lang]. Er is momenteel geen taalaanduiding aanwezig. Het advies is deze tekst in het Nederlands aan te bieden op deze pagina.

Dit zit niet in de componenten bibliotheek maar in de website, dit is tekstueel aan te passen in de html zoals te zien is [in de docs](https://componenten.nijmegen.nl/v6.3.2/components/detail/facets-advanced.html)
